import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  navbar: {
    backgroundColor: '#EEEEEE',
    padding: 20,
    flexDirection: 'row',
    // alignItems: 'center'
  },
  // Start Modal
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    fontFamily: 'Poppins-Bold',
    width: 200,
    color: 'black',
    fontSize: 25,
    marginBottom: 15,
    textAlign: 'center',
  },
  textStyles: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 24,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },

  button: {
    borderRadius: 20,
    width: 100,
    marginHorizontal: 10,
    padding: 10,
    elevation: 2,
    marginBottom: 10,
  },
  buttonss: {
    borderRadius: 10,
    width: 50,
    padding: 10,
    position: 'relative',
    left: 130,
    top: 48,
    zIndex: 1,
    // elevation: 2,
  },
  buttonClosed: {
    backgroundColor: '#e61919',
  },
  buttonClose: {
    backgroundColor: '#6A4029',
  },

  // End Modal
  scrolles: {
    // flex: 1,
    // display: 'flex',
    // justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: '#F9F9F9',
  },
  divup: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 50,
    marginBottom: 10,
    position: 'relative',
    top: -15,
  },
  wrapperSearch: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    marginTop: 30,
    marginLeft: 0,
    marginRight: 30,
    borderRadius: 15,
    backgroundColor: '#EFEEEE',
    elevation: 1,
    shadowColor: '#393939',
  },
  text: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: 'bold',
    fontSize: 18,
    color: '#6A5800',
  },

  textPlaceholder: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: 'bold',
    fontSize: 17,
    flex: 1,
    color: '#6A4029',
  },
  delete: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: 'bold',
    fontSize: 20,
    paddingRight: 20,
    color: '#black',
  },
  Icons1: {
    fontSize: 30,
    marginHorizontal: 3,
    color: 'grey',
  },
  icons: {
    marginRight: 30,
    color: 'black',
    fontSize: 25,
    marginTop: 3,
  },
  titleNavbar: {
    fontFamily: 'Poppins-Black',
    fontWeight: 'bold',
    color: 'black',
    fontSize: 18,
    position: 'relative',
    left: -20,
    top: -1,
  },
  cardfilter: {
    backgroundColor: '#3939391A',
    width: 70,
    borderRadius: 10,
    height: 30,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    top: 15,
  },
  category: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    fontSize: 28,
    color: 'black',
    textAlign: 'center',
    paddingTop: 15,
  },
  containerCard: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    // justifyContent: 'center',
    padding: 'auto',
    paddingTop: 25,
    marginHorizontal: 'auto',
    // marginHorizontal: 55,
  },
  card: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#3939391A',
    elevation: 1,
    width: 156,
    height: 212.41,
    borderRadius: 30,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    marginVertical: 30,
  },
  imgProduct: {
    width: 128.98,
    height: 128.98,
    borderRadius: 250,
    position: 'absolute',
    top: -35,
  },
  titleFood: {
    fontFamily: 'Poppins-Black',
    fontWeight: 'bold',
    fontSize: 22,
    textAlign: 'center',
    paddingTop: 90,
    // width: 116,
    lineHeight: 25,
    color: 'black',
  },
  priceFood: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    fontSize: 17,
    color: '#6A4029',
    textAlign: 'center',
  },
});

export default styles;
