import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 30,
    backgroundColor: '#F5F5F8',
  },
  navbar: {
    display: 'flex',
    flexDirection: 'row',
    // alignItems: 'center',
  },
  icons: {
    marginRight: 50,
    color: 'black',
    fontSize: 30,
    marginTop: 7,
  },
  titleNavbar: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    color: 'black',
    fontSize: 20,
  },
  TitleDelivery: {
    fontFamily: 'Poppins-Black',
    fontWeight: 'bold',
    color: 'black',
    fontSize: 34,
    // paddingBottom: 10,
  },
  TitleAddress: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    fontSize: 17,
    marginTop: 20,
    color: 'black',
  },
  CardAddress: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 20,
    marginVertical: 10,
  },
  CardStreet: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: 'bold',
    color: 'black',
    borderBottomColor: 'grey',
    borderBottomWidth: 0.5,
    paddingBottom: 5,
  },
  CardStreets: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: 'bold',
    color: 'black',
  },
  d: {
    fontFamily: 'Poppins-SemiBold',
    // fontWeight: 'bold',
    color: 'black',
    paddingLeft: 40,
  },
  colon: {
    paddingLeft: 55,
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: 'black',
  },
  CardStreetDetail: {
    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: 'black',
    paddingLeft: 5,
    width: 200,
  },
  contdel: {
    display: 'flex',
    flexDirection: 'row',
    borderBottomColor: 'grey',
    borderBottomWidth: 0.5,
    paddingBottom: 10,
    paddingTop: 10,
  },
  CardPhone: {
    paddingLeft: 15,

    fontFamily: 'Poppins-Regular',
    fontSize: 15,
    color: 'black',
  },
  CardMethods: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 20,
    marginVertical: 10,
    flexDirection: 'row',
  },
  radio: {
    display: 'flex',
    flexDirection: 'row',
    marginRight: 20,
    alignItems: 'center',
    marginVertical: 12.5,
  },
  checkedOuter: {
    width: 20,
    height: 20,
    borderColor: '#6A4029',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkedInner: {
    backgroundColor: '#6A4029',
    width: 10,
    height: 10,
    borderRadius: 50,
  },
  unchekedOuter: {
    width: 20,
    height: 20,
    borderColor: '#9F9F9F',
    borderWidth: 2,
    borderRadius: 100,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textMethod: {
    fontFamily: 'Poppins-Regular',
    fontSize: 17,
    color: 'black',
    marginBottom: 5,
    marginVertical: 11,
    width: 220,
  },
  total: {
    fontWeight: 'Poppins-Regular',
    fontSize: 17,
    color: 'black',
  },
  price: {
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
    fontSize: 22,
    color: 'black',
  },
});

export default styles;
