import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  sectionContainer: {
    flex: 1,
    backgroundColor: '#F2F2F2',
  },
  title: {
    // fontFamily: "Poppins-Bold",
    fontWeight: 'bold',
    fontSize: 34,
    color: 'black',
    width: 300,
    marginVertical: 20,
  },
  wrapperSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 30,
    // marginLeft: 40,
    marginRight: 25,
    borderRadius: 30,
    backgroundColor: '#EFEEEE',
    elevation: 1,
    shadowColor: '#393939',
  },
  Icons: {
    fontSize: 30,
    marginHorizontal: 3,
    color: 'grey',
  },
  iconSearch: {
    color: '#000',
    fontSize: 20,
    marginRight: 10,
  },
  textPlaceholder: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: 'bold',
    fontSize: 17,
    flex: 1,
    color: '#6A4029',
  },
  container: {
    marginTop: 10,
    paddingLeft: 20,
  },
  category: {
    // fontFamily: "Poppins-Bold",
    fontWeight: 'bold',
    color: '#6A4029',
    fontSize: 17,
    paddingBottom: 10,
    position: 'relative',
    top: 18,
  },
  card: {
    marginTop: 50,
    position: 'relative',
    backgroundColor: 'white',
    width: 220,
    height: 270,
    shadowColor: '#3939391A',
    elevation: 1,
    borderRadius: 30,
    marginHorizontal: 20,
  },
  imageCard: {
    width: 168,
    height: 169,
    borderRadius: 100,
    position: 'relative',
    left: 1,
  },
  containerImage: {
    position: 'relative',
    left: 25,
    top: -35,
  },
  containerTitle: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTitle: {
    // fontFamily: "Poppins-Bold",
    fontWeight: 'bold',
    fontSize: 22,
    color: 'black',
    textAlign: 'center',
    width: '100%',
    lineHeight: 25.29,
    paddingBottom: 5,
  },
  cardPrice: {
    // fontFamily: "Poppins-Bold",
    fontWeight: 'bold',
    fontSize: 17,
    color: '#6A4029',
  },
  see: {
    textAlign: 'right',
    paddingRight: 25,
    // fontFamily: 'Poppins-Reguler',
    fontSize: 15,
    color: '#6A4029',
    position: 'relative',
    top: -8,
  },
});

export default styles;
