import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  // Start Seacrh Modal
  divup: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginHorizontal: 50,
    marginBottom: 10,
    position: 'relative',
    top: -15,
  },
  icons: {
    marginRight: 30,
    color: 'black',
    fontSize: 25,
    marginTop: 3,
  },
  cardfilter: {
    backgroundColor: '#3939391A',
    width: 70,
    borderRadius: 10,
    height: 30,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    top: 15,
  },
  text: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: 'bold',
    fontSize: 18,
    color: '#6A5800',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    fontFamily: 'Poppins-Bold',
    width: 200,
    color: 'black',
    fontSize: 25,
    marginBottom: 15,
    textAlign: 'center',
  },
  textStyles: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 24,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },

  button: {
    borderRadius: 20,
    width: 100,
    marginHorizontal: 10,
    padding: 10,
    elevation: 2,
    marginBottom: 10,
  },
  buttonss: {
    borderRadius: 10,
    width: 50,
    padding: 10,
    position: 'relative',
    left: 130,
    top: 48,
    zIndex: 1,
    // elevation: 2,
  },
  buttonClosed: {
    backgroundColor: '#e61919',
  },
  buttonClose: {
    backgroundColor: '#6A4029',
  },
  // End Search Modal

  sectionContainer: {
    flex: 1,
    backgroundColor: '#F2F2F2',
  },
  title: {
    // fontFamily: "Poppins-Bold",
    fontWeight: 'bold',
    fontSize: 34,
    color: 'black',
    width: 300,
    marginVertical: 20,
  },
  wrapperSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 30,
    // marginLeft: 40,
    marginRight: 25,
    borderRadius: 30,
    backgroundColor: '#EFEEEE',
    elevation: 1,
    shadowColor: '#393939',
  },
  Icons: {
    fontSize: 30,
    marginHorizontal: 3,
    color: 'grey',
  },
  iconSearch: {
    color: '#000',
    fontSize: 20,
    marginRight: 10,
  },
  textPlaceholder: {
    fontFamily: 'Poppins-SemiBold',
    fontWeight: 'bold',
    fontSize: 17,
    flex: 1,
    color: '#6A4029',
  },
  container: {
    marginTop: 10,
    paddingLeft: 20,
  },
  category: {
    // fontFamily: "Poppins-Bold",
    fontWeight: 'bold',
    color: '#6A4029',
    fontSize: 20,
    paddingBottom: 10,
    position: 'relative',
    top: 18,
  },
  categorys: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingTop: 20,
    paddingBottom: 10,
  },
  nav_product_black: {
    borderBottomColor: `black`,
    borderBottomWidth: 2,
    color: `black`,
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 30,
    paddingHorizontal: 10,
    textAlign: `center`,
  },
  card: {
    marginTop: 50,
    position: 'relative',
    backgroundColor: 'white',
    width: 220,
    height: 270,
    shadowColor: '#3939391A',
    elevation: 1,
    borderRadius: 30,
    marginHorizontal: 20,
  },
  imageCard: {
    width: 168,
    height: 169,
    borderRadius: 100,
    position: 'relative',
    left: 1,
  },
  containerImage: {
    position: 'relative',
    left: 25,
    top: -35,
  },
  containerTitle: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTitle: {
    // fontFamily: "Poppins-Bold",
    fontWeight: 'bold',
    fontSize: 22,
    color: 'black',
    textAlign: 'center',
    width: '100%',
    lineHeight: 25.29,
    paddingBottom: 5,
  },
  cardPrice: {
    // fontFamily: "Poppins-Bold",
    fontWeight: 'bold',
    fontSize: 17,
    color: '#6A4029',
  },
  see: {
    textAlign: 'right',
    paddingRight: 25,
    // fontFamily: 'Poppins-Reguler',
    fontSize: 15,
    color: '#6A4029',
    position: 'relative',
    top: -8,
  },

  // Admin Page
  btnadd: {
    backgroundColor: '#f5c361',
    height: 60,
    width: 200,
    borderRadius: 10,
    marginBottom: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
